---
- block:
   - debug: msg="Start install Oracle Database software for {{ type_install }} type installation into home {{ oracledb.oracle_home }}"
   - block:  
      - debug: 
          msg: "{{ oracledb.ora_inventory_file }}"
      - name: Check existing oracle_home
        stat: 
          path: "{ oracledb.ora_inventory_file }}"
        register: inv
      - debug: var=inv      
      - lineinfile:
          path: "{ oracledb.ora_inventory_file }}"
          regexp: "^<HOME NAME.*{{ oracledb.oracle_home }}"
          state: absent
        check_mode: yes
        register: home_exists
        when: inv.stat.exists
      - fail:
          msg: "ORACLE_HOME={{ oracledb.oracle_home }} already exists!!! Please change ORACLE_HOME"
        when:  home_exists.changed  and home_exists is not skipped
     become: true
     tags:
       - check_oracle_home         
   - include_tasks: rac_install.yml
     when: type_install == 'db_rac'   
   - include_tasks: single_install.yml
     vars:
      _oraInv: "{{ inv.stat.exists|bool }}"
     when: type_install == 'db_single'     
  always:       
   - name: Clean stage directory
     file:
      path: "{{ oracle_distr }}" 
      state: absent
     become: true 